name = "receiptflow"
main = "src/index.ts"
compatibility_date = "2026-08-28"

[vars]
OPENROUTER_MODEL = "openrouter/free"

[[d1_databases]]
binding = "DB"
database_name = "receiptflow-db"
database_id = "7478ab69-8b59-47c2-beb7-7c8eb7649876"
